# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub }:

final: prev:
{
  firenvim = buildVimPluginFrom2Nix {
    pname = "firenvim";
    version = "2021-09-25";
    src = fetchFromGitHub {
      owner = "glacambre";
      repo = "firenvim";
      rev = "fa6406dc642e1ca5d63ba414398e983256ccbddb";
      sha256 = "0mr5fhqbhhgqqlka3npj9mcm5gkvr98w4gf8pl35dn3pzm1k781r";
    };
    meta.homepage = "https://github.com/glacambre/firenvim/";
  };

  nvim-markdown-preview = buildVimPluginFrom2Nix {
    pname = "nvim-markdown-preview";
    version = "2021-05-28";
    src = fetchFromGitHub {
      owner = "davidgranstrom";
      repo = "nvim-markdown-preview";
      rev = "d7cbefc69f93f55e376c4cb9d754390028659ea2";
      sha256 = "08yk58s2f10130n20i6fgnf8iyy6pwqv6siprbc0jqrn28pllpp9";
    };
    meta.homepage = "https://github.com/davidgranstrom/nvim-markdown-preview/";
  };

  nvim-tetris = buildVimPluginFrom2Nix {
    pname = "nvim-tetris";
    version = "2021-06-28";
    src = fetchFromGitHub {
      owner = "alec-gibson";
      repo = "nvim-tetris";
      rev = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
      sha256 = "057pmqhxk2vb3vwrydzjc1170c9dcnfasfaxklykhcwcjsmlbbzv";
    };
    meta.homepage = "https://github.com/alec-gibson/nvim-tetris/";
  };

  octo-nvim = buildVimPluginFrom2Nix {
    pname = "octo.nvim";
    version = "2021-08-23";
    src = fetchFromGitHub {
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "4ea1c65ba6f6059662f39d4a1d9ecd87d502729d";
      sha256 = "1v46n165q94k4cw8a5brkvcpzm7mbpbzmpz9czxcvkxrnbr6h0lc";
    };
    meta.homepage = "https://github.com/pwntester/octo.nvim/";
  };

  registers-nvim = buildVimPluginFrom2Nix {
    pname = "registers.nvim";
    version = "2021-09-09";
    src = fetchFromGitHub {
      owner = "tversteeg";
      repo = "registers.nvim";
      rev = "3f522bd7375dc780714c1ebe7fe398f4e45f0e52";
      sha256 = "013n3ci6605qa6dvabg02nhln9s5ahh9gvzh07w3ikvb53wp31h4";
    };
    meta.homepage = "https://github.com/tversteeg/registers.nvim/";
  };

  telescope-nvim = buildVimPluginFrom2Nix {
    pname = "telescope.nvim";
    version = "2021-09-26";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "4816a27d7680feed293d21a945c476947af20d29";
      sha256 = "0s0jlnjvk9qxvh91ghlhydry9lw9xc4jh5yy73190r9bbja3ix90";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope.nvim/";
  };

  vim-livedown = buildVimPluginFrom2Nix {
    pname = "vim-livedown";
    version = "2019-02-28";
    src = fetchFromGitHub {
      owner = "shime";
      repo = "vim-livedown";
      rev = "24c78c0c1177c0231bb542fa1e3807a3b089248e";
      sha256 = "0dnhxh4ifhvkp9a2vh7a97kc3dqcnh1jv3g8dlsxwy47zdhb0lnd";
    };
    meta.homepage = "https://github.com/shime/vim-livedown/";
  };

  vim-markdown-composer = buildVimPluginFrom2Nix {
    pname = "vim-markdown-composer";
    version = "2020-08-15";
    src = fetchFromGitHub {
      owner = "euclio";
      repo = "vim-markdown-composer";
      rev = "c0f98ec3d6c4cb49455c18f2aeb83c0dcbad1bc4";
      sha256 = "10vb3p8gksjy8zfzlkhirdsjwgvh1yv19plxwr404x87j393rs7n";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/euclio/vim-markdown-composer/";
  };

  vim-markdown-preview = buildVimPluginFrom2Nix {
    pname = "vim-markdown-preview";
    version = "2018-03-21";
    src = fetchFromGitHub {
      owner = "JamshedVesuna";
      repo = "vim-markdown-preview";
      rev = "9b3ec41fb6f0f49d9bb7ca81fa1c62a8a54b1214";
      sha256 = "04m452rfns9wxd2zmqqzjicysir6rn43yi736s05ss69wylhw2g3";
    };
    meta.homepage = "https://github.com/JamshedVesuna/vim-markdown-preview/";
  };

  virtual-types-nvim = buildVimPluginFrom2Nix {
    pname = "virtual-types.nvim";
    version = "2021-09-21";
    src = fetchFromGitHub {
      owner = "jubnzv";
      repo = "virtual-types.nvim";
      rev = "c51907c4160631c5f6da3cccd9f954e98fc9b7c8";
      sha256 = "1kv7wbyramvqn4ndjdmga5j3c8sm8nzmrzdi6chrdsjakpsg8rwl";
    };
    meta.homepage = "https://github.com/jubnzv/virtual-types.nvim/";
  };

}
